# Generated by Django 4.0.8 on 2022-12-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'Product is available to buy'), (1, 'Product is hidden')], default=0, verbose_name='Product Status'),
        ),
    ]
