# Generated by Django 4.0.8 on 2023-01-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_name_alter_category_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariety',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariety',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariety',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=5000, max_digits=10, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Quantity in stock'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductImageGallery',
        ),
        migrations.DeleteModel(
            name='ProductVariety',
        ),
    ]
