# Generated by Django 4.0.8 on 2022-12-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='products',
            field=models.ManyToManyField(to='products.product', verbose_name='Products with this variation'),
        ),
    ]
