# Generated by Django 4.0.8 on 2022-12-09 10:32

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rate', models.PositiveSmallIntegerField(verbose_name='Rate (from 10)')),
                ('title', models.CharField(max_length=100, verbose_name='Review Title')),
                ('context', models.TextField(verbose_name='Review Context')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
