# Generated by Django 4.0.8 on 2022-12-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_maincategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Main Category', 'verbose_name_plural': 'Main Categories'},
        ),
        migrations.AlterModelOptions(
            name='productimagegallery',
            options={'ordering': ['-priority'], 'verbose_name_plural': 'Product Images Gallery'},
        ),
        migrations.AlterModelOptions(
            name='productvariety',
            options={'ordering': ['-product'], 'verbose_name_plural': 'Product Varieties'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AddIndex(
            model_name='maincategory',
            index=models.Index(fields=['name'], name='shop_mainca_name_963d9b_idx'),
        ),
    ]
