# Generated by Django 4.0.8 on 2022-12-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(verbose_name='Discount Code')),
                ('rate', models.PositiveSmallIntegerField(verbose_name='Discount Percentage')),
                ('max_amount', models.PositiveIntegerField(verbose_name='Discount Max Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Promotion Name')),
                ('rate', models.PositiveSmallIntegerField(verbose_name='Discount Percentage')),
                ('max_amount', models.PositiveIntegerField(verbose_name='Discount Max Amount')),
                ('description', models.TextField(blank=True, verbose_name='Promotion Description')),
                ('item', models.ManyToManyField(to='products.productitem', verbose_name='Item To Promote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
