# Generated by Django 4.0.8 on 2022-12-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_phone_alter_profile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='national_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='National Code'),
        ),
    ]
